/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ComplianceRouteImport } from './routes/compliance'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as InvestigationRouteImport } from './routes/investigation'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SurveillanceRouteImport } from './routes/surveillance'
import { Route as TimelineRouteImport } from './routes/timeline'
import { Route as UploadRouteImport } from './routes/upload'
import { Route as CasesIndexRouteImport } from './routes/cases.index'
import { Route as CasesNewRouteImport } from './routes/cases.new'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ComplianceRoute = ComplianceRouteImport.update({
  id: '/compliance',
  path: '/compliance',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const InvestigationRoute = InvestigationRouteImport.update({
  id: '/investigation',
  path: '/investigation',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SurveillanceRoute = SurveillanceRouteImport.update({
  id: '/surveillance',
  path: '/surveillance',
  getParentRoute: () => rootRouteImport,
} as any)
const TimelineRoute = TimelineRouteImport.update({
  id: '/timeline',
  path: '/timeline',
  getParentRoute: () => rootRouteImport,
} as any)
const UploadRoute = UploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const CasesIndexRoute = CasesIndexRouteImport.update({
  id: '/cases/',
  path: '/cases/',
  getParentRoute: () => rootRouteImport,
} as any)
const CasesNewRoute = CasesNewRouteImport.update({
  id: '/cases/new',
  path: '/cases/new',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/compliance': typeof ComplianceRoute
  '/dashboard': typeof DashboardRoute
  '/investigation': typeof InvestigationRoute
  '/settings': typeof SettingsRoute
  '/surveillance': typeof SurveillanceRoute
  '/timeline': typeof TimelineRoute
  '/upload': typeof UploadRoute
  '/cases/new': typeof CasesNewRoute
  '/cases/': typeof CasesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/compliance': typeof ComplianceRoute
  '/dashboard': typeof DashboardRoute
  '/investigation': typeof InvestigationRoute
  '/settings': typeof SettingsRoute
  '/surveillance': typeof SurveillanceRoute
  '/timeline': typeof TimelineRoute
  '/upload': typeof UploadRoute
  '/cases/new': typeof CasesNewRoute
  '/cases': typeof CasesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/compliance': typeof ComplianceRoute
  '/dashboard': typeof DashboardRoute
  '/investigation': typeof InvestigationRoute
  '/settings': typeof SettingsRoute
  '/surveillance': typeof SurveillanceRoute
  '/timeline': typeof TimelineRoute
  '/upload': typeof UploadRoute
  '/cases/new': typeof CasesNewRoute
  '/cases/': typeof CasesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/compliance'
    | '/dashboard'
    | '/investigation'
    | '/settings'
    | '/surveillance'
    | '/timeline'
    | '/upload'
    | '/cases/new'
    | '/cases/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/compliance'
    | '/dashboard'
    | '/investigation'
    | '/settings'
    | '/surveillance'
    | '/timeline'
    | '/upload'
    | '/cases/new'
    | '/cases'
  id:
    | '__root__'
    | '/'
    | '/compliance'
    | '/dashboard'
    | '/investigation'
    | '/settings'
    | '/surveillance'
    | '/timeline'
    | '/upload'
    | '/cases/new'
    | '/cases/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ComplianceRoute: typeof ComplianceRoute
  DashboardRoute: typeof DashboardRoute
  InvestigationRoute: typeof InvestigationRoute
  SettingsRoute: typeof SettingsRoute
  SurveillanceRoute: typeof SurveillanceRoute
  TimelineRoute: typeof TimelineRoute
  UploadRoute: typeof UploadRoute
  CasesNewRoute: typeof CasesNewRoute
  CasesIndexRoute: typeof CasesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compliance': {
      id: '/compliance'
      path: '/compliance'
      fullPath: '/compliance'
      preLoaderRoute: typeof ComplianceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/investigation': {
      id: '/investigation'
      path: '/investigation'
      fullPath: '/investigation'
      preLoaderRoute: typeof InvestigationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/surveillance': {
      id: '/surveillance'
      path: '/surveillance'
      fullPath: '/surveillance'
      preLoaderRoute: typeof SurveillanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/timeline': {
      id: '/timeline'
      path: '/timeline'
      fullPath: '/timeline'
      preLoaderRoute: typeof TimelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/upload': {
      id: '/upload'
      path: '/upload'
      fullPath: '/upload'
      preLoaderRoute: typeof UploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cases/': {
      id: '/cases/'
      path: '/cases'
      fullPath: '/cases/'
      preLoaderRoute: typeof CasesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cases/new': {
      id: '/cases/new'
      path: '/cases/new'
      fullPath: '/cases/new'
      preLoaderRoute: typeof CasesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ComplianceRoute: ComplianceRoute,
  DashboardRoute: DashboardRoute,
  InvestigationRoute: InvestigationRoute,
  SettingsRoute: SettingsRoute,
  SurveillanceRoute: SurveillanceRoute,
  TimelineRoute: TimelineRoute,
  UploadRoute: UploadRoute,
  CasesNewRoute: CasesNewRoute,
  CasesIndexRoute: CasesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
